const cities = [
    "Alexander City, Alabama",
    "Andalusia, Alabama",
    "Anniston, Alabama",
    "Athens, Alabama",
    "Atmore, Alabama",
    "Auburn, Alabama",
    "Bessemer, Alabama",
    "Birmingham, Alabama",
    "Chickasaw, Alabama",
    "Clanton, Alabama",
    "Cullman, Alabama",
    "Decatur, Alabama",
    "Demopolis, Alabama",
    "Dothan, Alabama",
    "Enterprise, Alabama",
    "Eufaula, Alabama",
    "Florence, Alabama",
    "Fort Payne, Alabama",
    "Gadsden, Alabama",
    "Greenville, Alabama",
    "Guntersville, Alabama",
    "Huntsville, Alabama",
    "Jasper, Alabama",
    "Marion, Alabama",
    "Mobile, Alabama",
    "Montgomery, Alabama",
    "Opelika, Alabama",
    "Ozark, Alabama",
    "Phenix City, Alabama",
    "Prichard, Alabama",
    "Scottsboro, Alabama",
    "Selma, Alabama",
    "Sheffield, Alabama",
    "Sylacauga, Alabama",
    "Talladega, Alabama",
    "Troy, Alabama",
    "Tuscaloosa, Alabama",
    "Tuscumbia, Alabama",
    "Tuskegee, Alabama",
    "Anchorage, Alaska",
    "Cordova, Alaska",
    "Fairbanks, Alaska",
    "Haines, Alaska",
    "Homer, Alaska",
    "Juneau, Alaska",
    "Ketchikan, Alaska",
    "Kodiak, Alaska",
    "Kotzebue, Alaska",
    "Nome, Alaska",
    "Palmer, Alaska",
    "Seward, Alaska",
    "Sitka, Alaska",
    "Skagway, Alaska",
    "Valdez, Alaska",
    "Ajo, Arizona",
    "Avondale, Arizona",
    "Bisbee, Arizona",
    "Casa Grande, Arizona",
    "Chandler, Arizona",
    "Clifton, Arizona",
    "Douglas, Arizona",
    "Flagstaff, Arizona",
    "Florence, Arizona",
    "Gila Bend, Arizona",
    "Glendale, Arizona",
    "Globe, Arizona",
    "Kingman, Arizona",
    "Lake Havasu City, Arizona",
    "Mesa, Arizona",
    "Nogales, Arizona",
    "Oraibi, Arizona",
    "Phoenix, Arizona",
    "Prescott, Arizona",
    "Scottsdale, Arizona",
    "Sierra Vista, Arizona",
    "Tempe, Arizona",
    "Tombstone, Arizona",
    "Tucson, Arizona",
    "Walpi, Arizona",
    "Window Rock, Arizona",
    "Winslow, Arizona",
    "Yuma, Arizona",
    "Arkadelphia, Arkansas",
    "Arkansas Post, Arkansas",
    "Batesville, Arkansas",
    "Benton, Arkansas",
    "Blytheville, Arkansas",
    "Camden, Arkansas",
    "Conway, Arkansas",
    "Crossett, Arkansas",
    "El Dorado, Arkansas",
    "Fayetteville, Arkansas",
    "Forrest City, Arkansas",
    "Fort Smith, Arkansas",
    "Harrison, Arkansas",
    "Helena, Arkansas",
    "Hope, Arkansas",
    "Hot Springs, Arkansas",
    "Jacksonville, Arkansas",
    "Jonesboro, Arkansas",
    "Little Rock, Arkansas",
    "Magnolia, Arkansas",
    "Morrilton, Arkansas",
    "Newport, Arkansas",
    "North Little Rock, Arkansas",
    "Osceola, Arkansas",
    "Pine Bluff, Arkansas",
    "Rogers, Arkansas",
    "Searcy, Arkansas",
    "Stuttgart, Arkansas",
    "Van Buren, Arkansas",
    "West Memphis, Arkansas",
    "Alameda, California",
    "Alhambra, California",
    "Anaheim, California",
    "Antioch, California",
    "Arcadia, California",
    "Bakersfield, California",
    "Barstow, California",
    "Belmont, California",
    "Berkeley, California",
    "Beverly Hills, California",
    "Brea, California",
    "Buena Park, California",
    "Burbank, California",
    "Calexico, California",
    "Calistoga, California",
    "Carlsbad, California",
    "Carmel, California",
    "Chico, California",
    "Chula Vista, California",
    "Claremont, California",
    "Compton, California",
    "Concord, California",
    "Corona, California",
    "Coronado, California",
    "Costa Mesa, California",
    "Culver City, California",
    "Daly City, California",
    "Davis, California",
    "Downey, California",
    "El Centro, California",
    "El Cerrito, California",
    "El Monte, California",
    "Escondido, California",
    "Eureka, California",
    "Fairfield, California",
    "Fontana, California",
    "Fremont, California",
    "Fresno, California",
    "Fullerton, California",
    "Garden Grove, California",
    "Glendale, California",
    "Hayward, California",
    "Hollywood, California",
    "Huntington Beach, California",
    "Indio, California",
    "Inglewood, California",
    "Irvine, California",
    "La Habra, California",
    "Laguna Beach, California",
    "Lancaster, California",
    "Livermore, California",
    "Lodi, California",
    "Lompoc, California",
    "Long Beach, California",
    "Los Angeles, California",
    "Malibu, California",
    "Martinez, California",
    "Marysville, California",
    "Menlo Park, California",
    "Merced, California",
    "Modesto, California",
    "Monterey, California",
    "Mountain View, California",
    "Napa, California",
    "Needles, California",
    "Newport Beach, California",
    "Norwalk, California",
    "Novato, California",
    "Oakland, California",
    "Oceanside, California",
    "Ojai, California",
    "Ontario, California",
    "Orange, California",
    "Oroville, California",
    "Oxnard, California",
    "Pacific Grove, California",
    "Palm Springs, California",
    "Palmdale, California",
    "Palo Alto, California",
    "Pasadena, California",
    "Petaluma, California",
    "Pomona, California",
    "Port Hueneme, California",
    "Rancho Cucamonga, California",
    "Red Bluff, California",
    "Redding, California",
    "Redlands, California",
    "Redondo Beach, California",
    "Redwood City, California",
    "Richmond, California",
    "Riverside, California",
    "Roseville, California",
    "Sacramento, California",
    "Salinas, California",
    "San Bernardino, California",
    "San Clemente, California",
    "San Diego, California",
    "San Fernando, California",
    "San Francisco, California",
    "San Gabriel, California",
    "San Jose, California",
    "San Juan Capistrano, California",
    "San Leandro, California",
    "San Luis Obispo, California",
    "San Marino, California",
    "San Mateo, California",
    "San Pedro, California",
    "San Rafael, California",
    "San Simeon, California",
    "Santa Ana, California",
    "Santa Barbara, California",
    "Santa Clara, California",
    "Santa Clarita, California",
    "Santa Cruz, California",
    "Santa Monica, California",
    "Santa Rosa, California",
    "Sausalito, California",
    "Simi Valley, California",
    "Sonoma, California",
    "South San Francisco, California",
    "Stockton, California",
    "Sunnyvale, California",
    "Susanville, California",
    "Thousand Oaks, California",
    "Torrance, California",
    "Turlock, California",
    "Ukiah, California",
    "Vallejo, California",
    "Ventura, California",
    "Victorville, California",
    "Visalia, California",
    "Walnut Creek, California",
    "Watts, California",
    "West Covina, California",
    "Whittier, California",
    "Woodland, California",
    "Yorba Linda, California",
    "Yuba City, California",
    "Alamosa, Colorado",
    "Aspen, Colorado",
    "Aurora, Colorado",
    "Boulder, Colorado",
    "Breckenridge, Colorado",
    "Brighton, Colorado",
    "Canon City, Colorado",
    "Central City, Colorado",
    "Climax, Colorado",
    "Colorado Springs, Colorado",
    "Cortez, Colorado",
    "Cripple Creek, Colorado",
    "Denver, Colorado",
    "Durango, Colorado",
    "Englewood, Colorado",
    "Estes Park, Colorado",
    "Fort Collins, Colorado",
    "Fort Morgan, Colorado",
    "Georgetown, Colorado",
    "Glenwood Springs, Colorado",
    "Golden, Colorado",
    "Grand Junction, Colorado",
    "Greeley, Colorado",
    "Gunnison, Colorado",
    "La Junta, Colorado",
    "Leadville, Colorado",
    "Littleton, Colorado",
    "Longmont, Colorado",
    "Loveland, Colorado",
    "Montrose, Colorado",
    "Ouray, Colorado",
    "Pagosa Springs, Colorado",
    "Pueblo, Colorado",
    "Silverton, Colorado",
    "Steamboat Springs, Colorado",
    "Sterling, Colorado",
    "Telluride, Colorado",
    "Trinidad, Colorado",
    "Vail, Colorado",
    "Walsenburg, Colorado",
    "Westminster, Colorado",
    "Ansonia, Connecticut",
    "Berlin, Connecticut",
    "Bloomfield, Connecticut",
    "Branford, Connecticut",
    "Bridgeport, Connecticut",
    "Bristol, Connecticut",
    "Coventry, Connecticut",
    "Danbury, Connecticut",
    "Darien, Connecticut",
    "Derby, Connecticut",
    "East Hartford, Connecticut",
    "East Haven, Connecticut",
    "Enfield, Connecticut",
    "Fairfield, Connecticut",
    "Farmington, Connecticut",
    "Greenwich, Connecticut",
    "Groton, Connecticut",
    "Guilford, Connecticut",
    "Hamden, Connecticut",
    "Hartford, Connecticut",
    "Lebanon, Connecticut",
    "Litchfield, Connecticut",
    "Manchester, Connecticut",
    "Mansfield, Connecticut",
    "Meriden, Connecticut",
    "Middletown, Connecticut",
    "Milford, Connecticut",
    "Mystic, Connecticut",
    "Naugatuck, Connecticut",
    "New Britain, Connecticut",
    "New Haven, Connecticut",
    "New London, Connecticut",
    "North Haven, Connecticut",
    "Norwalk, Connecticut",
    "Norwich, Connecticut",
    "Old Saybrook, Connecticut",
    "Orange, Connecticut",
    "Seymour, Connecticut",
    "Shelton, Connecticut",
    "Simsbury, Connecticut",
    "Southington, Connecticut",
    "Stamford, Connecticut",
    "Stonington, Connecticut",
    "Stratford, Connecticut",
    "Torrington, Connecticut",
    "Wallingford, Connecticut",
    "Waterbury, Connecticut",
    "Waterford, Connecticut",
    "Watertown, Connecticut",
    "West Hartford, Connecticut",
    "West Haven, Connecticut",
    "Westport, Connecticut",
    "Wethersfield, Connecticut",
    "Willimantic, Connecticut",
    "Windham, Connecticut",
    "Windsor, Connecticut",
    "Windsor Locks, Connecticut",
    "Winsted, Connecticut",
    "Dover, Delaware",
    "Lewes, Delaware",
    "Milford, Delaware",
    "New Castle, Delaware",
    "Newark, Delaware",
    "Smyrna, Delaware",
    "Wilmington, Delaware",
    "Apalachicola, Florida",
    "Bartow, Florida",
    "Belle Glade, Florida",
    "Boca Raton, Florida",
    "Bradenton, Florida",
    "Cape Coral, Florida",
    "Clearwater, Florida",
    "Cocoa Beach, Florida",
    "Cocoa-Rockledge, Florida",
    "Coral Gables, Florida",
    "Daytona Beach, Florida",
    "De Land, Florida",
    "Deerfield Beach, Florida",
    "Delray Beach, Florida",
    "Fernandina Beach, Florida",
    "Fort Lauderdale, Florida",
    "Fort Myers, Florida",
    "Fort Pierce, Florida",
    "Fort Walton Beach, Florida",
    "Gainesville, Florida",
    "Hallandale Beach, Florida",
    "Hialeah, Florida",
    "Hollywood, Florida",
    "Homestead, Florida",
    "Jacksonville, Florida",
    "Key West, Florida",
    "Lake City, Florida",
    "Lake Wales, Florida",
    "Lakeland, Florida",
    "Largo, Florida",
    "Melbourne, Florida",
    "Miami, Florida",
    "Miami Beach, Florida",
    "Naples, Florida",
    "New Smyrna Beach, Florida",
    "Ocala, Florida",
    "Orlando, Florida",
    "Ormond Beach, Florida",
    "Palatka, Florida",
    "Palm Bay, Florida",
    "Palm Beach, Florida",
    "Panama City, Florida",
    "Pensacola, Florida",
    "Pompano Beach, Florida",
    "Saint Augustine, Florida",
    "Saint Petersburg, Florida",
    "Sanford, Florida",
    "Sarasota, Florida",
    "Sebring, Florida",
    "Tallahassee, Florida",
    "Tampa, Florida",
    "Tarpon Springs, Florida",
    "Titusville, Florida",
    "Venice, Florida",
    "West Palm Beach, Florida",
    "White Springs, Florida",
    "Winter Haven, Florida",
    "Winter Park, Florida",
    "Albany, Georgia",
    "Americus, Georgia",
    "Andersonville, Georgia",
    "Athens, Georgia",
    "Atlanta, Georgia",
    "Augusta, Georgia",
    "Bainbridge, Georgia",
    "Blairsville, Georgia",
    "Brunswick, Georgia",
    "Calhoun, Georgia",
    "Carrollton, Georgia",
    "Columbus, Georgia",
    "Dahlonega, Georgia",
    "Dalton, Georgia",
    "Darien, Georgia",
    "Decatur, Georgia",
    "Douglas, Georgia",
    "East Point, Georgia",
    "Fitzgerald, Georgia",
    "Fort Valley, Georgia",
    "Gainesville, Georgia",
    "La Grange, Georgia",
    "Macon, Georgia",
    "Marietta, Georgia",
    "Milledgeville, Georgia",
    "Plains, Georgia",
    "Rome, Georgia",
    "Savannah, Georgia",
    "Toccoa, Georgia",
    "Valdosta, Georgia",
    "Warm Springs, Georgia",
    "Warner Robins, Georgia",
    "Waycross, Washington",
    "Hanalei, Hawaii",
    "Hilo, Hawaii",
    "Honaunau, Hawaii",
    "Honolulu, Hawaii",
    "Kahului, Hawaii",
    "Kaneohe, Hawaii",
    "Kapaa, Hawaii",
    "Kawaihae, Hawaii",
    "Lahaina, Hawaii",
    "Laie, Hawaii",
    "Wahiawa, Hawaii",
    "Wailuku, Hawaii",
    "Waimea, Hawaii",
    "Blackfoot, Idaho",
    "Boise, Idaho",
    "Bonners Ferry, Idaho",
    "Caldwell, Idaho",
    "Coeur d’Alene, Idaho",
    "Idaho City, Idaho",
    "Idaho Falls, Idaho",
    "Kellogg, Idaho",
    "Lewiston, Idaho",
    "Moscow, Idaho",
    "Nampa, Idaho",
    "Pocatello, Idaho",
    "Priest River, Idaho",
    "Rexburg, Idaho",
    "Sun Valley, Idaho",
    "Twin Falls, Idaho",
    "Alton, Illinois",
    "Arlington Heights, Illinois",
    "Arthur, Illinois",
    "Aurora, Illinois",
    "Belleville, Illinois",
    "Belvidere, Illinois",
    "Bloomington, Illinois",
    "Brookfield, Illinois",
    "Cahokia, Illinois",
    "Cairo, Illinois",
    "Calumet City, Illinois",
    "Canton, Illinois",
    "Carbondale, Illinois",
    "Carlinville, Illinois",
    "Carthage, Illinois",
    "Centralia, Illinois",
    "Champaign, Illinois",
    "Charleston, Illinois",
    "Chester, Illinois",
    "Chicago, Illinois",
    "Chicago Heights, Illinois",
    "Cicero, Illinois",
    "Collinsville, Illinois",
    "Danville, Illinois",
    "Decatur, Illinois",
    "DeKalb, Illinois",
    "Des Plaines, Illinois",
    "Dixon, Illinois",
    "East Moline, Illinois",
    "East Saint Louis, Illinois",
    "Effingham, Illinois",
    "Elgin, Illinois",
    "Elmhurst, Illinois",
    "Evanston, Illinois",
    "Freeport, Illinois",
    "Galena, Illinois",
    "Galesburg, Illinois",
    "Glen Ellyn, Illinois",
    "Glenview, Illinois",
    "Granite City, Illinois",
    "Harrisburg, Illinois",
    "Herrin, Illinois",
    "Highland Park, Illinois",
    "Jacksonville, Illinois",
    "Joliet, Illinois",
    "Kankakee, Illinois",
    "Kaskaskia, Illinois",
    "Kewanee, Illinois",
    "La Salle, Illinois",
    "Lake Forest, Illinois",
    "Libertyville, Illinois",
    "Lincoln, Illinois",
    "Lisle, Illinois",
    "Lombard, Illinois",
    "Macomb, Illinois",
    "Mattoon, Illinois",
    "Moline, Illinois",
    "Monmouth, Illinois",
    "Mount Vernon, Illinois",
    "Mundelein, Illinois",
    "Naperville, Illinois",
    "Nauvoo, Illinois",
    "Normal, Illinois",
    "North Chicago, Illinois",
    "Oak Park, Illinois",
    "Ottawa, Oregon",
    "Palatine, Oregon",
    "Park Forest, Oregon",
    "Park Ridge, Oregon",
    "Pekin, Oregon",
    "Peoria, Oregon",
    "Petersburg, Oregon",
    "Pontiac, Oregon",
    "Quincy, Oregon",
    "Rantoul, Oregon",
    "River Forest, Oregon",
    "Rock Island, Oregon",
    "Rockford, Oregon",
    "Salem, Oregon",
    "Shawneetown, Oregon",
    "Skokie, Oregon",
    "South Holland, Oregon",
    "Springfield, Oregon",
    "Streator, Oregon",
    "Summit, Oregon",
    "Urbana, Oregon",
    "Vandalia, Oregon",
    "Virden, Oregon",
    "Waukegan, Oregon",
    "Wheaton, Oregon",
    "Wilmette, Oregon",
    "Winnetka, Oregon",
    "Wood River, Oregon",
    "Zion, Oregon",
    "Anderson, Indiana",
    "Bedford, Indiana",
    "Bloomington, Indiana",
    "Columbus, Indiana",
    "Connersville, Indiana",
    "Corydon, Indiana",
    "Crawfordsville, Indiana",
    "East Chicago, Indiana",
    "Elkhart, Indiana",
    "Elwood, Indiana",
    "Evansville, Indiana",
    "Fort Wayne, Indiana",
    "French Lick, Indiana",
    "Gary, Indiana",
    "Geneva, Indiana",
    "Goshen, Indiana",
    "Greenfield, Indiana",
    "Hammond, Indiana",
    "Hobart, Indiana",
    "Huntington, Indiana",
    "Indianapolis, Indiana",
    "Jeffersonville, Indiana",
    "Kokomo, Indiana",
    "Lafayette, Indiana",
    "Madison, Indiana",
    "Marion, Indiana",
    "Michigan City, Indiana",
    "Mishawaka, Indiana",
    "Muncie, Indiana",
    "Nappanee, Indiana",
    "Nashville, Indiana",
    "New Albany, Indiana",
    "New Castle, Indiana",
    "New Harmony, Indiana",
    "Peru, Indiana",
    "Plymouth, Indiana",
    "Richmond, Indiana",
    "Santa Claus, Indiana",
    "Shelbyville, Indiana",
    "South Bend, Indiana",
    "Terre Haute, Indiana",
    "Valparaiso, Indiana",
    "Vincennes, Indiana",
    "Wabash, Indiana",
    "West Lafayette, Indiana",
    "Amana Colonies, Iowa",
    "Ames, Iowa",
    "Boone, Iowa",
    "Burlington, Iowa",
    "Cedar Falls, Iowa",
    "Cedar Rapids, Iowa",
    "Charles City, Iowa",
    "Cherokee, Iowa",
    "Clinton, Iowa",
    "Council Bluffs, Iowa",
    "Davenport, Iowa",
    "Des Moines, Iowa",
    "Dubuque, Iowa",
    "Estherville, Iowa",
    "Fairfield, Iowa",
    "Fort Dodge, Iowa",
    "Grinnell, Iowa",
    "Indianola, Iowa",
    "Iowa City, Iowa",
    "Keokuk, Iowa",
    "Mason City, Iowa",
    "Mount Pleasant, Iowa",
    "Muscatine, Iowa",
    "Newton, Iowa",
    "Oskaloosa, Iowa",
    "Ottumwa, Iowa",
    "Sioux City, Iowa",
    "Waterloo, Iowa",
    "Webster City, Iowa",
    "West Des Moines, Iowa",
    "Abilene, Kansas",
    "Arkansas City, Kansas",
    "Atchison, Kansas",
    "Chanute, Kansas",
    "Coffeyville, Kansas",
    "Council Grove, Kansas",
    "Dodge City, Kansas",
    "Emporia, Kansas",
    "Fort Scott, Kansas",
    "Garden City, Kansas",
    "Great Bend, Kansas",
    "Hays, Kansas",
    "Hutchinson, Kansas",
    "Independence, Kansas",
    "Junction City, Kansas",
    "Kansas City, Kansas",
    "Lawrence, Kansas",
    "Leavenworth, Kansas",
    "Liberal, Kansas",
    "Manhattan, Kansas",
    "McPherson, Kansas",
    "Medicine Lodge, Kansas",
    "Newton, Kansas",
    "Olathe, Kansas",
    "Osawatomie, Kansas",
    "Ottawa, Kansas",
    "Overland Park, Kansas",
    "Pittsburg, Kansas",
    "Salina, Kansas",
    "Shawnee, Kansas",
    "Smith Center, Kansas",
    "Topeka, Kansas",
    "Wichita, Kansas",
    "Ashland, Kentucky",
    "Barbourville, Kentucky",
    "Bardstown, Kentucky",
    "Berea, Kentucky",
    "Boonesborough, Kentucky",
    "Bowling Green, Kentucky",
    "Campbellsville, Kentucky",
    "Covington, Kentucky",
    "Danville, Kentucky",
    "Elizabethtown, Kentucky",
    "Frankfort, Kentucky",
    "Harlan, Kentucky",
    "Harrodsburg, Kentucky",
    "Hazard, Kentucky",
    "Henderson, Kentucky",
    "Hodgenville, Kentucky",
    "Hopkinsville, Kentucky",
    "Lexington, Kentucky",
    "Louisville, Kentucky",
    "Mayfield, Kentucky",
    "Maysville, Kentucky",
    "Middlesboro, Kentucky",
    "Newport, Kentucky",
    "Owensboro, Kentucky",
    "Paducah, Kentucky",
    "Paris, Kentucky",
    "Richmond, Kentucky",
    "Abbeville, Louisiana",
    "Alexandria, Louisiana",
    "Bastrop, Louisiana",
    "Baton Rouge, Louisiana",
    "Bogalusa, Louisiana",
    "Bossier City, Louisiana",
    "Gretna, Louisiana",
    "Houma, Louisiana",
    "Lafayette, Louisiana",
    "Lake Charles, Louisiana",
    "Monroe, Louisiana",
    "Morgan City, Louisiana",
    "Natchitoches, Louisiana",
    "New Iberia, Louisiana",
    "New Orleans, Louisiana",
    "Opelousas, Louisiana",
    "Ruston, Louisiana",
    "Saint Martinville, Louisiana",
    "Shreveport, Louisiana",
    "Thibodaux, Louisiana",
    "Auburn, Maine",
    "Augusta, Maine",
    "Bangor, Maine",
    "Bar Harbor, Maine",
    "Bath, Maine",
    "Belfast, Maine",
    "Biddeford, Maine",
    "Boothbay Harbor, Maine",
    "Brunswick, Maine",
    "Calais, Maine",
    "Caribou, Maine",
    "Castine, Maine",
    "Eastport, Maine",
    "Ellsworth, Maine",
    "Farmington, Maine",
    "Fort Kent, Maine",
    "Gardiner, Maine",
    "Houlton, Maine",
    "Kennebunkport, Maine",
    "Kittery, Maine",
    "Lewiston, Maine",
    "Lubec, Maine",
    "Machias, Maine",
    "Orono, Maine",
    "Portland, Maine",
    "Presque Isle, Maine",
    "Rockland, Maine",
    "Rumford, Maine",
    "Saco, Maine",
    "Scarborough, Maine",
    "Waterville, Maine",
    "York, Maine",
    "Aberdeen, Maryland",
    "Annapolis, Maryland",
    "Baltimore, Maryland",
    "Bethesda-Chevy Chase, Maryland",
    "Bowie, Maryland",
    "Cambridge, Maryland",
    "Catonsville, Maryland",
    "College Park, Maryland",
    "Columbia, Maryland",
    "Cumberland, Maryland",
    "Easton, Maryland",
    "Elkton, Maryland",
    "Emmitsburg, Maryland",
    "Frederick, Maryland",
    "Greenbelt, Maryland",
    "Hagerstown, Maryland",
    "Hyattsville, Maryland",
    "Laurel, Maryland",
    "Oakland, Maryland",
    "Ocean City, Maryland",
    "Rockville, Maryland",
    "Saint Marys City, Maryland",
    "Salisbury, Maryland",
    "Silver Spring, Maryland",
    "Takoma Park, Maryland",
    "Towson, Maryland",
    "Westminster, Maryland",
    "Abington, Massachusetts",
    "Adams, Massachusetts",
    "Amesbury, Massachusetts",
    "Amherst, Massachusetts",
    "Andover, Massachusetts",
    "Arlington, Massachusetts",
    "Athol, Massachusetts",
    "Attleboro, Massachusetts",
    "Barnstable, Massachusetts",
    "Bedford, Massachusetts",
    "Beverly, Massachusetts",
    "Boston, Massachusetts",
    "Bourne, Massachusetts",
    "Braintree, Massachusetts",
    "Brockton, Massachusetts",
    "Brookline, Massachusetts",
    "Cambridge, Massachusetts",
    "Canton, Massachusetts",
    "Charlestown, Massachusetts",
    "Chelmsford, Massachusetts",
    "Chelsea, Massachusetts",
    "Chicopee, Massachusetts",
    "Clinton, Massachusetts",
    "Cohasset, Massachusetts",
    "Concord, Massachusetts",
    "Danvers, Massachusetts",
    "Dartmouth, Massachusetts",
    "Dedham, Massachusetts",
    "Dennis, Massachusetts",
    "Duxbury, Massachusetts",
    "Eastham, Massachusetts",
    "Edgartown, Massachusetts",
    "Everett, Massachusetts",
    "Fairhaven, Massachusetts",
    "Fall River, Massachusetts",
    "Falmouth, Massachusetts",
    "Fitchburg, Massachusetts",
    "Framingham, Massachusetts",
    "Gloucester, Massachusetts",
    "Great Barrington, Massachusetts",
    "Greenfield, Massachusetts",
    "Groton, Massachusetts",
    "Harwich, Massachusetts",
    "Haverhill, Massachusetts",
    "Hingham, Massachusetts",
    "Holyoke, Massachusetts",
    "Hyannis, Massachusetts",
    "Ipswich, Massachusetts",
    "Lawrence, Massachusetts",
    "Lenox, Massachusetts",
    "Leominster, Massachusetts",
    "Lexington, Massachusetts",
    "Lowell, Massachusetts",
    "Ludlow, Massachusetts",
    "Lynn, Massachusetts",
    "Malden, Massachusetts",
    "Marblehead, Massachusetts",
    "Marlborough, Massachusetts",
    "Medford, Massachusetts",
    "Milton, Massachusetts",
    "Nahant, Massachusetts",
    "Natick, Massachusetts",
    "New Bedford, Massachusetts",
    "Newburyport, Massachusetts",
    "Newton, Massachusetts",
    "North Adams, Massachusetts",
    "Northampton, Massachusetts",
    "Norton, Massachusetts",
    "Norwood, Massachusetts",
    "Peabody, Massachusetts",
    "Pittsfield, Massachusetts",
    "Plymouth, Massachusetts",
    "Provincetown, Massachusetts",
    "Quincy, Massachusetts",
    "Randolph, Massachusetts",
    "Revere, Massachusetts",
    "Salem, Massachusetts",
    "Sandwich, Massachusetts",
    "Saugus, Massachusetts",
    "Somerville, Massachusetts",
    "South Hadley, Massachusetts",
    "Springfield, Massachusetts",
    "Stockbridge, Massachusetts",
    "Stoughton, Massachusetts",
    "Sturbridge, Massachusetts",
    "Sudbury, Massachusetts",
    "Taunton, Massachusetts",
    "Tewksbury, Massachusetts",
    "Truro, Massachusetts",
    "Watertown, Massachusetts",
    "Webster, Massachusetts",
    "Wellesley, Massachusetts",
    "Wellfleet, Massachusetts",
    "West Bridgewater, Massachusetts",
    "West Springfield, Massachusetts",
    "Westfield, Massachusetts",
    "Weymouth, Massachusetts",
    "Whitman, Massachusetts",
    "Williamstown, Massachusetts",
    "Woburn, Massachusetts",
    "Woods Hole, Massachusetts",
    "Worcester, Massachusetts",
    "Adrian, Michigan",
    "Alma, Michigan",
    "Ann Arbor, Michigan",
    "Battle Creek, Michigan",
    "Bay City, Michigan",
    "Benton Harbor, Michigan",
    "Bloomfield Hills, Michigan",
    "Cadillac, Michigan",
    "Charlevoix, Michigan",
    "Cheboygan, Michigan",
    "Dearborn, Michigan",
    "Detroit, Michigan",
    "East Lansing, Michigan",
    "Eastpointe, Michigan",
    "Ecorse, Michigan",
    "Escanaba, Michigan",
    "Flint, Michigan",
    "Grand Haven, Michigan",
    "Grand Rapids, Michigan",
    "Grayling, Michigan",
    "Grosse Pointe, Michigan",
    "Hancock, Michigan",
    "Highland Park, Michigan",
    "Holland, Michigan",
    "Houghton, Michigan",
    "Interlochen, Michigan",
    "Iron Mountain, Michigan",
    "Ironwood, Michigan",
    "Ishpeming, Michigan",
    "Jackson, Michigan",
    "Kalamazoo, Michigan",
    "Lansing, Michigan",
    "Livonia, Michigan",
    "Ludington, Michigan",
    "Mackinaw City, Michigan",
    "Manistee, Michigan",
    "Marquette, Michigan",
    "Menominee, Michigan",
    "Midland, Michigan",
    "Monroe, Michigan",
    "Mount Clemens, Michigan",
    "Mount Pleasant, Michigan",
    "Muskegon, Michigan",
    "Niles, Michigan",
    "Petoskey, Michigan",
    "Pontiac, Michigan",
    "Port Huron, Michigan",
    "Royal Oak, Michigan",
    "Saginaw, Michigan",
    "Saint Ignace, Michigan",
    "Saint Joseph, Michigan",
    "Sault Sainte Marie, Michigan",
    "Traverse City, Michigan",
    "Trenton, Michigan",
    "Warren, Michigan",
    "Wyandotte, Michigan",
    "Ypsilanti, Michigan",
    "Albert Lea, Minnesota",
    "Alexandria, Minnesota",
    "Austin, Minnesota",
    "Bemidji, Minnesota",
    "Bloomington, Minnesota",
    "Brainerd, Minnesota",
    "Crookston, Minnesota",
    "Duluth, Minnesota",
    "Ely, Minnesota",
    "Eveleth, Minnesota",
    "Faribault, Minnesota",
    "Fergus Falls, Minnesota",
    "Hastings, Minnesota",
    "Hibbing, Minnesota",
    "International Falls, Minnesota",
    "Little Falls, Minnesota",
    "Mankato, Minnesota",
    "Minneapolis, Minnesota",
    "Moorhead, Minnesota",
    "New Ulm, Minnesota",
    "Northfield, Minnesota",
    "Owatonna, Minnesota",
    "Pipestone, Minnesota",
    "Red Wing, Minnesota",
    "Rochester, Minnesota",
    "Saint Cloud, Minnesota",
    "Saint Paul, Minnesota",
    "Sauk Centre, Minnesota",
    "South Saint Paul, Minnesota",
    "Stillwater, Minnesota",
    "Willmar, Virginia",
    "Winona, Virginia",
    "Bay Saint Louis, Mississippi",
    "Biloxi, Mississippi",
    "Canton, Mississippi",
    "Clarksdale, Mississippi",
    "Columbia, Mississippi",
    "Columbus, Mississippi",
    "Corinth, Mississippi",
    "Greenville, Mississippi",
    "Greenwood, Mississippi",
    "Grenada, Mississippi",
    "Gulfport, Mississippi",
    "Hattiesburg, Mississippi",
    "Holly Springs, Mississippi",
    "Jackson, Mississippi",
    "Laurel, Mississippi",
    "Meridian, Mississippi",
    "Natchez, Mississippi",
    "Ocean Springs, Mississippi",
    "Oxford, Mississippi",
    "Pascagoula, Mississippi",
    "Pass Christian, Mississippi",
    "Philadelphia, Mississippi",
    "Port Gibson, Mississippi",
    "Starkville, Mississippi",
    "Tupelo, Mississippi",
    "Vicksburg, Mississippi",
    "West Point, Mississippi",
    "Yazoo City, Mississippi",
    "Boonville, Missouri",
    "Branson, Missouri",
    "Cape Girardeau, Missouri",
    "Carthage, Missouri",
    "Chillicothe, Missouri",
    "Clayton, Missouri",
    "Columbia, Missouri",
    "Excelsior Springs, Missouri",
    "Ferguson, Missouri",
    "Florissant, Missouri",
    "Fulton, Missouri",
    "Hannibal, Missouri",
    "Independence, Missouri",
    "Jefferson City, Missouri",
    "Joplin, Missouri",
    "Kansas City, Missouri",
    "Kirksville, Missouri",
    "Lamar, Missouri",
    "Lebanon, Missouri",
    "Lexington, Missouri",
    "Maryville, Missouri",
    "Mexico, Missouri",
    "Monett, Missouri",
    "Neosho, Missouri",
    "New Madrid, Missouri",
    "Rolla, Missouri",
    "Saint Charles, Missouri",
    "Saint Joseph, Missouri",
    "Saint Louis, Missouri",
    "Sainte Genevieve, Missouri",
    "Salem, Missouri",
    "Sedalia, Missouri",
    "Springfield, Missouri",
    "Warrensburg, Missouri",
    "West Plains, Missouri",
    "Anaconda, Montana",
    "Billings, Montana",
    "Bozeman, Montana",
    "Butte, Montana",
    "Dillon, Montana",
    "Fort Benton, Montana",
    "Glendive, Montana",
    "Great Falls, Montana",
    "Havre, Montana",
    "Helena, Montana",
    "Kalispell, Montana",
    "Lewistown, Montana",
    "Livingston, Montana",
    "Miles City, Montana",
    "Missoula, Montana",
    "Virginia City, Montana",
    "Beatrice, Nebraska",
    "Bellevue, Nebraska",
    "Boys Town, Nebraska",
    "Chadron, Nebraska",
    "Columbus, Nebraska",
    "Fremont, Nebraska",
    "Grand Island, Nebraska",
    "Hastings, Nebraska",
    "Kearney, Nebraska",
    "Lincoln, Nebraska",
    "McCook, Nebraska",
    "Minden, Nebraska",
    "Nebraska City, Nebraska",
    "Norfolk, Nebraska",
    "North Platte, Nebraska",
    "Omaha, Nebraska",
    "Plattsmouth, Nebraska",
    "Red Cloud, Nebraska",
    "Sidney, Nebraska",
    "Boulder City, Nevada",
    "Carson City, Nevada",
    "Elko, Nevada",
    "Ely, Nevada",
    "Fallon, Nevada",
    "Genoa, Nevada",
    "Goldfield, Nevada",
    "Henderson, Nevada",
    "Las Vegas, Nevada",
    "North Las Vegas, Nevada",
    "Reno, Nevada",
    "Sparks, Nevada",
    "Virginia City, Nevada",
    "Winnemucca, Nevada",
    "Berlin, New Hampshire",
    "Claremont, New Hampshire",
    "Concord, New Hampshire",
    "Derry, New Hampshire",
    "Dover, New Hampshire",
    "Durham, New Hampshire",
    "Exeter, New Hampshire",
    "Franklin, New Hampshire",
    "Hanover, New Hampshire",
    "Hillsborough, New Hampshire",
    "Keene, New Hampshire",
    "Laconia, New Hampshire",
    "Lebanon, New Hampshire",
    "Manchester, New Hampshire",
    "Nashua, New Hampshire",
    "Peterborough, New Hampshire",
    "Plymouth, New Hampshire",
    "Portsmouth, New Hampshire",
    "Rochester, New Hampshire",
    "Salem, New Hampshire",
    "Somersworth, New Hampshire",
    "Asbury Park, New Jersey",
    "Atlantic City, New Jersey",
    "Bayonne, New Jersey",
    "Bloomfield, New Jersey",
    "Bordentown, New Jersey",
    "Bound Brook, New Jersey",
    "Bridgeton, New Jersey",
    "Burlington, New Jersey",
    "Caldwell, New Jersey",
    "Camden, New Jersey",
    "Cape May, New Jersey",
    "Clifton, New Jersey",
    "Cranford, New Jersey",
    "East Orange, New Jersey",
    "Edison, New Jersey",
    "Elizabeth, New Jersey",
    "Englewood, New Jersey",
    "Fort Lee, New Jersey",
    "Glassboro, New Jersey",
    "Hackensack, New Jersey",
    "Haddonfield, New Jersey",
    "Hoboken, New Jersey",
    "Irvington, New Jersey",
    "Jersey City, New Jersey",
    "Lakehurst, New Jersey",
    "Lakewood, New Jersey",
    "Long Beach, New Jersey",
    "Long Branch, New Jersey",
    "Madison, New Jersey",
    "Menlo Park, New Jersey",
    "Millburn, New Jersey",
    "Millville, New Jersey",
    "Montclair, New Jersey",
    "Morristown, New Jersey",
    "Mount Holly, New Jersey",
    "New Brunswick, New Jersey",
    "New Milford, New Jersey",
    "Newark, New Jersey",
    "Ocean City, New Jersey",
    "Orange, New Jersey",
    "Parsippany–Troy Hills, New Jersey",
    "Passaic, New Jersey",
    "Paterson, New Jersey",
    "Perth Amboy, New Jersey",
    "Plainfield, New Jersey",
    "Princeton, New Jersey",
    "Ridgewood, New Jersey",
    "Roselle, New Jersey",
    "Rutherford, New Jersey",
    "Salem, New Jersey",
    "Somerville, New Jersey",
    "South Orange Village, New Jersey",
    "Totowa, New Jersey",
    "Trenton, New Jersey",
    "Union, New Jersey",
    "Union City, New Jersey",
    "Vineland, New Jersey",
    "Wayne, New Jersey",
    "Weehawken, New Jersey",
    "West New York, New Jersey",
    "West Orange, New Jersey",
    "Willingboro, New Jersey",
    "Woodbridge, New Jersey",
    "Acoma, New Mexico",
    "Alamogordo, New Mexico",
    "Albuquerque, New Mexico",
    "Artesia, New Mexico",
    "Belen, New Mexico",
    "Carlsbad, New Mexico",
    "Clovis, New Mexico",
    "Deming, New Mexico",
    "Farmington, New Mexico",
    "Gallup, New Mexico",
    "Grants, New Mexico",
    "Hobbs, New Mexico",
    "Las Cruces, New Mexico",
    "Las Vegas, New Mexico",
    "Los Alamos, New Mexico",
    "Lovington, New Mexico",
    "Portales, New Mexico",
    "Raton, New Mexico",
    "Roswell, New Mexico",
    "Santa Fe, New Mexico",
    "Shiprock, New Mexico",
    "Silver City, New Mexico",
    "Socorro, New Mexico",
    "Taos, New Mexico",
    "Truth or Consequences, New Mexico",
    "Tucumcari, New Mexico",
    "Albany, New York",
    "Amsterdam, New York",
    "Auburn, New York",
    "Babylon, New York",
    "Batavia, New York",
    "Beacon, New York",
    "Bedford, New York",
    "Binghamton, New York",
    "Bronx, New York",
    "Brooklyn, New York",
    "Buffalo, New York",
    "Chautauqua, New York",
    "Cheektowaga, New York",
    "Clinton, New York",
    "Cohoes, New York",
    "Coney Island, New York",
    "Cooperstown, New York",
    "Corning, New York",
    "Cortland, New York",
    "Crown Point, New York",
    "Dunkirk, New York",
    "East Aurora, New York",
    "East Hampton, New York",
    "Eastchester, New York",
    "Elmira, New York",
    "Flushing, New York",
    "Forest Hills, New York",
    "Fredonia, New York",
    "Garden City, New York",
    "Geneva, New York",
    "Glens Falls, New York",
    "Gloversville, New York",
    "Great Neck, New York",
    "Hammondsport, New York",
    "Harlem, New York",
    "Hempstead, New York",
    "Herkimer, New York",
    "Hudson, New York",
    "Huntington, New York",
    "Hyde Park, New York",
    "Ilion, New York",
    "Ithaca, New York",
    "Jamestown, New York",
    "Johnstown, New York",
    "Kingston, New York",
    "Lackawanna, New York",
    "Lake Placid, New York",
    "Levittown, New York",
    "Lockport, New York",
    "Mamaroneck, New York",
    "Manhattan, New York",
    "Massena, New York",
    "Middletown, New York",
    "Mineola, New York",
    "Mount Vernon, New York",
    "New Paltz, New York",
    "New Rochelle, New York",
    "New Windsor, New York",
    "New York City, New York",
    "Newburgh, New York",
    "Niagara Falls, New York",
    "North Hempstead, New York",
    "Nyack, New York",
    "Ogdensburg, New York",
    "Olean, New York",
    "Oneida, New York",
    "Oneonta, New York",
    "Ossining, New York",
    "Oswego, New York",
    "Oyster Bay, New York",
    "Palmyra, New York",
    "Peekskill, New York",
    "Plattsburgh, New York",
    "Port Washington, New York",
    "Potsdam, New York",
    "Poughkeepsie, New York",
    "Queens, New York",
    "Rensselaer, New York",
    "Rochester, New York",
    "Rome, New York",
    "Rotterdam, New York",
    "Rye, New York",
    "Sag Harbor, New York",
    "Saranac Lake, New York",
    "Saratoga Springs, New York",
    "Scarsdale, New York",
    "Schenectady, New York",
    "Seneca Falls, New York",
    "Southampton, New York",
    "Staten Island, New York",
    "Stony Brook, New York",
    "Stony Point, New York",
    "Syracuse, New York",
    "Tarrytown, New York",
    "Ticonderoga, New York",
    "Tonawanda, New York",
    "Troy, New York",
    "Utica, New York",
    "Watertown, New York",
    "Watervliet, New York",
    "Watkins Glen, New York",
    "West Seneca, New York",
    "White Plains, New York",
    "Woodstock, New York",
    "Yonkers, New York",
    "Asheboro, North Carolina",
    "Asheville, North Carolina",
    "Bath, North Carolina",
    "Beaufort, North Carolina",
    "Boone, North Carolina",
    "Burlington, North Carolina",
    "Chapel Hill, North Carolina",
    "Charlotte, North Carolina",
    "Concord, North Carolina",
    "Durham, North Carolina",
    "Edenton, North Carolina",
    "Elizabeth City, North Carolina",
    "Fayetteville, North Carolina",
    "Gastonia, North Carolina",
    "Goldsboro, North Carolina",
    "Greensboro, North Carolina",
    "Greenville, North Carolina",
    "Halifax, North Carolina",
    "Henderson, North Carolina",
    "Hickory, North Carolina",
    "High Point, North Carolina",
    "Hillsborough, North Carolina",
    "Jacksonville, North Carolina",
    "Kinston, North Carolina",
    "Kitty Hawk, North Carolina",
    "Lumberton, North Carolina",
    "Morehead City, North Carolina",
    "Morganton, North Carolina",
    "Nags Head, North Carolina",
    "New Bern, North Carolina",
    "Pinehurst, North Carolina",
    "Raleigh, North Carolina",
    "Rocky Mount, North Carolina",
    "Salisbury, North Carolina",
    "Shelby, North Carolina",
    "Wilmington, Washington",
    "Wilson, Washington",
    "Winston-Salem, Washington",
    "Bismarck, North Dakota",
    "Devils Lake, North Dakota",
    "Dickinson, North Dakota",
    "Fargo, North Dakota",
    "Grand Forks, North Dakota",
    "Jamestown, North Dakota",
    "Mandan, North Dakota",
    "Minot, North Dakota",
    "Rugby, North Dakota",
    "Valley City, North Dakota",
    "Wahpeton, North Dakota",
    "Williston, North Dakota",
    "Akron, Ohio",
    "Alliance, Ohio",
    "Ashtabula, Ohio",
    "Athens, Ohio",
    "Barberton, Ohio",
    "Bedford, Ohio",
    "Bellefontaine, Ohio",
    "Bowling Green, Ohio",
    "Canton, Ohio",
    "Chillicothe, Ohio",
    "Cincinnati, Ohio",
    "Cleveland, Ohio",
    "Cleveland Heights, Ohio",
    "Columbus, Ohio",
    "Conneaut, Ohio",
    "Cuyahoga Falls, Ohio",
    "Dayton, Ohio",
    "Defiance, Ohio",
    "East Cleveland, Delaware",
    "East Liverpool, Delaware",
    "Elyria, Delaware",
    "Euclid, Delaware",
    "Findlay, Delaware",
    "Gallipolis, Delaware",
    "Greenville, Delaware",
    "Hamilton, Delaware",
    "Kent, Delaware",
    "Kettering, Delaware",
    "Lakewood, Delaware",
    "Lancaster, Delaware",
    "Lima, Delaware",
    "Lorain, Delaware",
    "Mansfield, Delaware",
    "Marietta, Delaware",
    "Marion, Delaware",
    "Martins Ferry, Delaware",
    "Massillon, Delaware",
    "Mentor, Delaware",
    "Middletown, Delaware",
    "Milan, Delaware",
    "Mount Vernon, Delaware",
    "New Philadelphia, Delaware",
    "Newark, Delaware",
    "Niles, Delaware",
    "North College Hill, Delaware",
    "Norwalk, Delaware",
    "Oberlin, Delaware",
    "Painesville, Delaware",
    "Parma, Delaware",
    "Piqua, Delaware",
    "Portsmouth, Delaware",
    "Put-in-Bay, Delaware",
    "Salem, Delaware",
    "Sandusky, Delaware",
    "Shaker Heights, Delaware",
    "Springfield, Delaware",
    "Steubenville, Delaware",
    "Tiffin, Delaware",
    "Toledo, Delaware",
    "Urbana, Delaware",
    "Warren, Delaware",
    "Wooster, Delaware",
    "Worthington, Delaware",
    "Xenia, Delaware",
    "Yellow Springs, Delaware",
    "Youngstown, Delaware",
    "Zanesville, Delaware",
    "Ada, Oklahoma",
    "Altus, Oklahoma",
    "Alva, Oklahoma",
    "Anadarko, Oklahoma",
    "Ardmore, Oklahoma",
    "Bartlesville, Oklahoma",
    "Bethany, Oklahoma",
    "Chickasha, Oklahoma",
    "Claremore, Oklahoma",
    "Clinton, Oklahoma",
    "Cushing, Oklahoma",
    "Duncan, Oklahoma",
    "Durant, Oklahoma",
    "Edmond, Oklahoma",
    "El Reno, Oklahoma",
    "Elk City, Oklahoma",
    "Enid, Oklahoma",
    "Eufaula, Oklahoma",
    "Frederick, Oklahoma",
    "Guthrie, Oklahoma",
    "Guymon, Oklahoma",
    "Hobart, Oklahoma",
    "Holdenville, Oklahoma",
    "Hugo, Oklahoma",
    "Lawton, Oklahoma",
    "McAlester, Oklahoma",
    "Miami, Oklahoma",
    "Midwest City, Oklahoma",
    "Moore, Oklahoma",
    "Muskogee, Oklahoma",
    "Norman, Oklahoma",
    "Oklahoma City, Oklahoma",
    "Okmulgee, Oklahoma",
    "Pauls Valley, Oklahoma",
    "Pawhuska, Oklahoma",
    "Perry, Oklahoma",
    "Ponca City, Oklahoma",
    "Pryor, Oklahoma",
    "Sallisaw, Oklahoma",
    "Sand Springs, Oklahoma",
    "Sapulpa, Oklahoma",
    "Seminole, Oklahoma",
    "Shawnee, Oklahoma",
    "Stillwater, Oklahoma",
    "Tahlequah, Oklahoma",
    "The Village, Oklahoma",
    "Tulsa, Oklahoma",
    "Vinita, Oklahoma",
    "Wewoka, Oklahoma",
    "Woodward, Oklahoma",
    "Albany, Oregon",
    "Ashland, Oregon",
    "Astoria, Oregon",
    "Baker City, Oregon",
    "Beaverton, Oregon",
    "Bend, Oregon",
    "Brookings, Oregon",
    "Burns, Oregon",
    "Coos Bay, Oregon",
    "Corvallis, Oregon",
    "Eugene, Oregon",
    "Grants Pass, Oregon",
    "Hillsboro, Oregon",
    "Hood River, Oregon",
    "Jacksonville, Oregon",
    "John Day, Oregon",
    "Klamath Falls, Oregon",
    "La Grande, Oregon",
    "Lake Oswego, Oregon",
    "Lakeview, Oregon",
    "McMinnville, Oregon",
    "Medford, Oregon",
    "Newberg, Oregon",
    "Newport, Oregon",
    "Ontario, Oregon",
    "Oregon City, Oregon",
    "Pendleton, Oregon",
    "Port Orford, Oregon",
    "Portland, Oregon",
    "Prineville, Oregon",
    "Redmond, Oregon",
    "Reedsport, Oregon",
    "Roseburg, Oregon",
    "Salem, Oregon",
    "Seaside, Oregon",
    "Springfield, Oregon",
    "The Dalles, Oregon",
    "Tillamook, Oregon",
    "Abington, Pennsylvania",
    "Aliquippa, Pennsylvania",
    "Allentown, Pennsylvania",
    "Altoona, Pennsylvania",
    "Ambridge, Pennsylvania",
    "Bedford, Pennsylvania",
    "Bethlehem, Pennsylvania",
    "Bloomsburg, Pennsylvania",
    "Bradford, Pennsylvania",
    "Bristol, Pennsylvania",
    "Carbondale, Pennsylvania",
    "Carlisle, Pennsylvania",
    "Chambersburg, Pennsylvania",
    "Chester, Pennsylvania",
    "Columbia, Pennsylvania",
    "Easton, Pennsylvania",
    "Erie, Pennsylvania",
    "Franklin, Pennsylvania",
    "Germantown, Pennsylvania",
    "Gettysburg, Pennsylvania",
    "Greensburg, Pennsylvania",
    "Hanover, Pennsylvania",
    "Harmony, Pennsylvania",
    "Harrisburg, Pennsylvania",
    "Hazleton, Pennsylvania",
    "Hershey, Pennsylvania",
    "Homestead, Pennsylvania",
    "Honesdale, Pennsylvania",
    "Jeannette, Indiana",
    "Jim Thorpe, Indiana",
    "Johnstown, Indiana",
    "Lancaster, Indiana",
    "Lebanon, Indiana",
    "Levittown, Indiana",
    "Lewistown, Indiana",
    "Lock Haven, Indiana",
    "Lower Southampton, Indiana",
    "McKeesport, Indiana",
    "Meadville, Indiana",
    "Middletown, Indiana",
    "Monroeville, Indiana",
    "Nanticoke, Indiana",
    "New Castle, Indiana",
    "New Hope, Indiana",
    "New Kensington, Indiana",
    "Norristown, Indiana",
    "Oil City, Indiana",
    "Philadelphia, Indiana",
    "Phoenixville, Indiana",
    "Pittsburgh, Indiana",
    "Pottstown, Indiana",
    "Pottsville, Indiana",
    "Reading, Indiana",
    "Scranton, Indiana",
    "Shamokin, Indiana",
    "Sharon, Indiana",
    "State College, Indiana",
    "Stroudsburg, Indiana",
    "Sunbury, Indiana",
    "Swarthmore, Indiana",
    "Tamaqua, Indiana",
    "Titusville, Indiana",
    "Uniontown, Indiana",
    "Warren, Indiana",
    "West Chester, Washington",
    "Wilkes-Barre, Washington",
    "Williamsport, Washington",
    "York, Washington",
    "Barrington, Rhode Island",
    "Bristol, Rhode Island",
    "Central Falls, Rhode Island",
    "Cranston, Rhode Island",
    "East Greenwich, Rhode Island",
    "East Providence, Rhode Island",
    "Kingston, Rhode Island",
    "Middletown, Rhode Island",
    "Narragansett, Rhode Island",
    "Newport, Rhode Island",
    "North Kingstown, Rhode Island",
    "Pawtucket, Rhode Island",
    "Portsmouth, Rhode Island",
    "Providence, Rhode Island",
    "South Kingstown, Rhode Island",
    "Tiverton, Rhode Island",
    "Warren, Rhode Island",
    "Warwick, Rhode Island",
    "Westerly, Rhode Island",
    "Wickford, Rhode Island",
    "Woonsocket, Rhode Island",
    "Abbeville, South Carolina",
    "Aiken, South Carolina",
    "Anderson, South Carolina",
    "Beaufort, South Carolina",
    "Camden, South Carolina",
    "Charleston, South Carolina",
    "Columbia, South Carolina",
    "Darlington, South Carolina",
    "Florence, South Carolina",
    "Gaffney, South Carolina",
    "Georgetown, South Carolina",
    "Greenville, South Carolina",
    "Greenwood, South Carolina",
    "Hartsville, South Carolina",
    "Lancaster, South Carolina",
    "Mount Pleasant, South Carolina",
    "Myrtle Beach, South Carolina",
    "Orangeburg, South Carolina",
    "Rock Hill, South Carolina",
    "Spartanburg, South Carolina",
    "Sumter, South Carolina",
    "Union, South Carolina",
    "Aberdeen, South Dakota",
    "Belle Fourche, South Dakota",
    "Brookings, South Dakota",
    "Canton, South Dakota",
    "Custer, South Dakota",
    "De Smet, South Dakota",
    "Deadwood, South Dakota",
    "Hot Springs, South Dakota",
    "Huron, South Dakota",
    "Lead, South Dakota",
    "Madison, South Dakota",
    "Milbank, South Dakota",
    "Mitchell, South Dakota",
    "Mobridge, South Dakota",
    "Pierre, South Dakota",
    "Rapid City, South Dakota",
    "Sioux Falls, South Dakota",
    "Spearfish, South Dakota",
    "Sturgis, South Dakota",
    "Vermillion, South Dakota",
    "Watertown, South Dakota",
    "Yankton, South Dakota",
    "Alcoa, Tennessee",
    "Athens, Tennessee",
    "Chattanooga, Tennessee",
    "Clarksville, Tennessee",
    "Cleveland, Tennessee",
    "Columbia, Tennessee",
    "Cookeville, Tennessee",
    "Dayton, Tennessee",
    "Elizabethton, Tennessee",
    "Franklin, Tennessee",
    "Gallatin, Tennessee",
    "Gatlinburg, Tennessee",
    "Greeneville, Tennessee",
    "Jackson, Tennessee",
    "Johnson City, Tennessee",
    "Jonesborough, Tennessee",
    "Kingsport, Tennessee",
    "Knoxville, Tennessee",
    "Lebanon, Tennessee",
    "Maryville, Tennessee",
    "Memphis, Tennessee",
    "Morristown, Tennessee",
    "Murfreesboro, Tennessee",
    "Nashville, Tennessee",
    "Norris, Tennessee",
    "Oak Ridge, Tennessee",
    "Shelbyville, Tennessee",
    "Tullahoma, Tennessee",
    "Abilene, Texas",
    "Alpine, Texas",
    "Amarillo, Texas",
    "Arlington, Texas",
    "Austin, Texas",
    "Baytown, Texas",
    "Beaumont, Texas",
    "Big Spring, Texas",
    "Borger, Texas",
    "Brownsville, Texas",
    "Bryan, Texas",
    "Canyon, Texas",
    "Cleburne, Texas",
    "College Station, Texas",
    "Corpus Christi, Texas",
    "Crystal City, Texas",
    "Dallas, Texas",
    "Del Rio, Texas",
    "Denison, Texas",
    "Denton, Texas",
    "Eagle Pass, Texas",
    "Edinburg, Texas",
    "El Paso, Texas",
    "Fort Worth, Texas",
    "Freeport, Texas",
    "Galveston, Texas",
    "Garland, Texas",
    "Goliad, Texas",
    "Greenville, Texas",
    "Harlingen, Texas",
    "Houston, Texas",
    "Huntsville, Texas",
    "Irving, Texas",
    "Johnson City, Texas",
    "Kilgore, Texas",
    "Killeen, Texas",
    "Kingsville, Texas",
    "Laredo, Texas",
    "Longview, Texas",
    "Lubbock, Texas",
    "Lufkin, Texas",
    "Marshall, Texas",
    "McAllen, Texas",
    "McKinney, Texas",
    "Mesquite, Texas",
    "Midland, Texas",
    "Mission, Texas",
    "Nacogdoches, Texas",
    "New Braunfels, Texas",
    "Odessa, Texas",
    "Orange, Texas",
    "Pampa, Texas",
    "Paris, Texas",
    "Pasadena, Texas",
    "Pecos, Texas",
    "Pharr, Texas",
    "Plainview, Texas",
    "Plano, Texas",
    "Port Arthur, Texas",
    "Port Lavaca, Texas",
    "Richardson, Texas",
    "San Angelo, Texas",
    "San Antonio, Texas",
    "San Felipe, Texas",
    "San Marcos, Texas",
    "Sherman, Texas",
    "Sweetwater, Texas",
    "Temple, Texas",
    "Texarkana, Texas",
    "Texas City, Texas",
    "Tyler, Texas",
    "Uvalde, Texas",
    "Victoria, Texas",
    "Waco, Texas",
    "Weatherford, Texas",
    "Wichita Falls, Texas",
    "Ysleta, Texas",
    "Alta, Utah",
    "American Fork, Utah",
    "Bountiful, Utah",
    "Brigham City, Utah",
    "Cedar City, Utah",
    "Clearfield, Utah",
    "Delta, Utah",
    "Fillmore, Utah",
    "Green River, Utah",
    "Heber City, Utah",
    "Kanab, Utah",
    "Layton, Utah",
    "Lehi, Utah",
    "Logan, Utah",
    "Manti, Utah",
    "Moab, Utah",
    "Monticello, Utah",
    "Murray, Utah",
    "Nephi, Utah",
    "Ogden, Utah",
    "Orderville, Utah",
    "Orem, Utah",
    "Panguitch, Utah",
    "Park City, Utah",
    "Payson, Utah",
    "Price, Utah",
    "Provo, Utah",
    "Saint George, Utah",
    "Salt Lake City, Utah",
    "Spanish Fork, Utah",
    "Springville, Utah",
    "Tooele, Utah",
    "Vernal, Utah",
    "Barre, Vermont",
    "Bellows Falls, Vermont",
    "Bennington, Vermont",
    "Brattleboro, Vermont",
    "Burlington, Vermont",
    "Essex, Vermont",
    "Manchester, Vermont",
    "Middlebury, Vermont",
    "Montpelier, Vermont",
    "Newport, Vermont",
    "Plymouth, Vermont",
    "Rutland, Vermont",
    "Saint Albans, Vermont",
    "Saint Johnsbury, Vermont",
    "Sharon, Vermont",
    "Winooski, Vermont",
    "Abingdon, Virginia",
    "Alexandria, Virginia",
    "Bristol, Virginia",
    "Charlottesville, Virginia",
    "Chesapeake, Virginia",
    "Danville, Virginia",
    "Fairfax, Virginia",
    "Falls Church, Virginia",
    "Fredericksburg, Virginia",
    "Hampton, Virginia",
    "Hanover, Virginia",
    "Hopewell, Virginia",
    "Lexington, Virginia",
    "Lynchburg, Virginia",
    "Manassas, Virginia",
    "Martinsville, Virginia",
    "New Market, Virginia",
    "Newport News, Virginia",
    "Norfolk, Virginia",
    "Petersburg, Virginia",
    "Portsmouth, Virginia",
    "Reston, Virginia",
    "Richmond, Virginia",
    "Roanoke, Virginia",
    "Staunton, Virginia",
    "Suffolk, Virginia",
    "Virginia Beach, Virginia",
    "Waynesboro, Virginia",
    "Williamsburg, Virginia",
    "Winchester, Virginia",
    "Aberdeen, Washington",
    "Anacortes, Washington",
    "Auburn, Washington",
    "Bellevue, Washington",
    "Bellingham, Washington",
    "Bremerton, Washington",
    "Centralia, Washington",
    "Coulee Dam, Washington",
    "Coupeville, Washington",
    "Ellensburg, Washington",
    "Ephrata, Washington",
    "Everett, Washington",
    "Hoquiam, Washington",
    "Kelso, Washington",
    "Kennewick, Washington",
    "Longview, Washington",
    "Moses Lake, Washington",
    "Oak Harbor, Washington",
    "Olympia, Washington",
    "Pasco, Washington",
    "Point Roberts, Washington",
    "Port Angeles, Washington",
    "Pullman, Washington",
    "Puyallup, Washington",
    "Redmond, Washington",
    "Renton, Washington",
    "Richland, Washington",
    "Seattle, Washington",
    "Spokane, Washington",
    "Tacoma, Washington",
    "Vancouver, Washington",
    "Walla Walla, Washington",
    "Wenatchee, Washington",
    "Yakima, Washington",
    "Bath, West Virginia",
    "Beckley, West Virginia",
    "Bluefield, West Virginia",
    "Buckhannon, West Virginia",
    "Charles Town, West Virginia",
    "Charleston, West Virginia",
    "Clarksburg, West Virginia",
    "Elkins, West Virginia",
    "Fairmont, West Virginia",
    "Grafton, West Virginia",
    "Harpers Ferry, West Virginia",
    "Hillsboro, West Virginia",
    "Hinton, West Virginia",
    "Huntington, West Virginia",
    "Keyser, West Virginia",
    "Lewisburg, West Virginia",
    "Logan, West Virginia",
    "Martinsburg, West Virginia",
    "Morgantown, West Virginia",
    "Moundsville, West Virginia",
    "New Martinsville, West Virginia",
    "Parkersburg, West Virginia",
    "Philippi, West Virginia",
    "Point Pleasant, West Virginia",
    "Princeton, West Virginia",
    "Romney, West Virginia",
    "Shepherdstown, West Virginia",
    "South Charleston, West Virginia",
    "Summersville, West Virginia",
    "Weirton, West Virginia",
    "Welch, West Virginia",
    "Wellsburg, West Virginia",
    "Weston, West Virginia",
    "Wheeling, West Virginia",
    "White Sulphur Springs, West Virginia",
    "Williamson, West Virginia",
    "Appleton, Wisconsin",
    "Ashland, Wisconsin",
    "Baraboo, Wisconsin",
    "Belmont, Wisconsin",
    "Beloit, Wisconsin",
    "Eau Claire, Wisconsin",
    "Fond du Lac, Wisconsin",
    "Green Bay, Wisconsin",
    "Hayward, Wisconsin",
    "Janesville, Wisconsin",
    "Kenosha, Wisconsin",
    "La Crosse, Wisconsin",
    "Lake Geneva, Wisconsin",
    "Madison, Wisconsin",
    "Manitowoc, Wisconsin",
    "Marinette, Wisconsin",
    "Menasha, Wisconsin",
    "Milwaukee, Wisconsin",
    "Neenah, Wisconsin",
    "New Glarus, Wisconsin",
    "Oconto, Wisconsin",
    "Oshkosh, Wisconsin",
    "Peshtigo, Wisconsin",
    "Portage, Wisconsin",
    "Prairie du Chien, Wisconsin",
    "Racine, Wisconsin",
    "Rhinelander, Wisconsin",
    "Ripon, Wisconsin",
    "Sheboygan, Wisconsin",
    "Spring Green, Wisconsin",
    "Stevens Point, Wisconsin",
    "Sturgeon Bay, Wisconsin",
    "Superior, Wisconsin",
    "Waukesha, Wisconsin",
    "Wausau, Wisconsin",
    "Wauwatosa, Wisconsin",
    "West Allis, Wisconsin",
    "West Bend, Wisconsin",
    "Wisconsin Dells, Wisconsin",
    "Buffalo, Wyoming",
    "Casper, Wyoming",
    "Cheyenne, Wyoming",
    "Cody, Wyoming",
    "Douglas, Wyoming",
    "Evanston, Wyoming",
    "Gillette, Wyoming",
    "Green River, Wyoming",
    "Jackson, Wyoming",
    "Lander, Wyoming",
    "Laramie, Wyoming",
    "Newcastle, Wyoming",
    "Powell, Wyoming",
    "Rawlins, Wyoming",
    "Riverton, Wyoming",
    "Rock Springs, Wyoming",
    "Sheridan, Wyoming",
    "Ten Sleep, Wyoming",
    "Thermopolis, Wyoming",
    "Torrington, Wyoming",
    "Worland, Wyoming",
];


export default cities;