const ntee_codes = {
    "A01": "Alliance/Advocacy Organizations",
    "A02": "Management & Technical Assistance",
    "A03": "Professional Societies & Associations",
    "A05": "Research Institutes & Public Policy Analysis",
    "A11": "Single Organization Support",
    "A12": "Fund Raising & Fund Distribution",
    "A19": "Nonmonetary Support N.E.C.",
    "A20": "Arts & Culture",
    "A23": "Cultural & Ethnic Awareness",
    "A24": "Folk Arts",
    "A25": "Arts Education",
    "A26": "Arts & Humanities Councils & Agencies",
    "A27": "Community Celebrations",
    "A30": "Media & Communications",
    "A31": "Film & Video",
    "A32": "Television",
    "A33": "Printing & Publishing",
    "A34": "Radio",
    "A40": "Visual Arts",
    "A50": "Museum & Museum Activities",
    "A51": "Art Museums",
    "A52": "Children's Museums",
    "A53": "Folk Arts Museums",
    "A54": "History Museums",
    "A60": "Performing Arts",
    "A61": "Performing Arts Centers",
    "A62": "Dance",
    "A63": "Ballet",
    "A65": "Theater",
    "A68": "Music",
    "A69": "Symphony Orchestras",
    "A70": "Humanities",
    "A80": "Historical Organizations",
    "A84": "Commemorative Events",
    "A90": "Arts Services",
    "A99": "Arts, Culture & Humanities N.E.C.",
    "B01": "Alliance/Advocacy Organizations",
    "B02": "Management & Technical Assistance",
    "B03": "Professional Societies & Associations",
    "B05": "Research Institutes & Public Policy Analysis",
    "B11": "Single Organization Support",
    "B12": "Fund Raising & Fund Distribution",
    "B19": "Nonmonetary Support N.E.C.",
    "B20": "Elementary & Secondary Schools",
    "B21": "Kindergarten, Preschool, Nursery School, Early Admissions",
    "B24": "Primary & Elementary Schools",
    "B25": "Secondary & High Schools",
    "B26": "Charter Schools",
    "B27": "Special Education",
    "B28": "Specialized Educational Institutions",
    "B29": "Religiously Affiliated/Supported Schools",
    "B30": "Vocational & Technical Schools",
    "B40": "Higher Education Institutions",
    "B41": "Community or Junior Colleges",
    "B42": "Undergraduate Colleges",
    "B43": "Universities",
    "B50": "Graduate & Professional Schools",
    "B60": "Adult Education",
    "B70": "Libraries",
    "B80": "Student Services",
    "B82": "Scholarships & Student Financial Aid",
    "B83": "Student Sororities & Fraternities",
    "B84": "Alumni Associations",
    "B90": "Educational Services",
    "B92": "Remedial Reading & Encouragement",
    "B94": "Parent & Teacher Groups",
    "B99": "Education N.E.C.",
    "C01": "Alliance/Advocacy Organizations",
    "C02": "Management & Technical Assistance",
    "C03": "Professional Societies & Associations",
    "C05": "Research Institutes & Public Policy Analysis",
    "C11": "Single Organization Support",
    "C12": "Fund Raising & Fund Distribution",
    "C19": "Nonmonetary Support N.E.C.",
    "C20": "Pollution Abatement & Control Services",
    "C27": "Recycling",
    "C30": "Natural Resources Conservation & Protection",
    "C32": "Water Resource, Wetlands Conservation & Management",
    "C34": "Land Resources Conservation",
    "C35": "Energy Resources Conservation & Development",
    "C36": "Forest Conservation",
    "C40": "Botanical, Horticultural & Landscape Services",
    "C41": "Garden Clubs",
    "C42": "Garden & Horticultural Programs",
    "C50": "Environmental Beautification",
    "C60": "Environmental Education & Outdoor Survival Programs",
    "C61": "Environmental Interpretation & Information",
    "C62": "Environmental Science",
    "C99": "Environmental Quality, Protection & Beautification N.E.C.",
    "D01": "Alliance/Advocacy Organizations",
    "D02": "Management & Technical Assistance",
    "D03": "Professional Societies & Associations",
    "D05": "Research Institutes & Public Policy Analysis",
    "D11": "Single Organization Support",
    "D12": "Fund Raising & Fund Distribution",
    "D19": "Nonmonetary Support N.E.C.",
    "D20": "Animal Protection & Welfare",
    "D30": "Wildlife Preservation & Protection",
    "D31": "Protection of Endangered Species",
    "D32": "Bird Sanctuaries",
    "D33": "Fisheries Resources",
    "D34": "Wildlife Sanctuaries",
    "D40": "Veterinary Services",
    "D50": "Zoos & Aquariums",
    "D60": "Animal Training, Behavior & Enrichment",
    "D61": "Animal Training",
    "D62": "Pet Therapy",
    "D70": "Animal Rights",
    "D80": "Animal Services",
    "D99": "Animal-Related N.E.C.",
    "E01": "Alliance/Advocacy Organizations",
    "E02": "Management & Technical Assistance",
    "E03": "Professional Societies & Associations",
    "E05": "Research Institutes & Public Policy Analysis",
    "E11": "Single Organization Support",
    "E12": "Fund Raising & Fund Distribution",
    "E19": "Nonmonetary Support N.E.C.",
    "E20": "Hospitals & Health Care",
    "E21": "Community Health Systems",
    "E22": "General & Rehabilitative Hospitals",
    "E24": "Specialty Hospitals",
    "E30": "Health Treatment Facilities, Primarily Outpatient",
    "E31": "Group Health Practices",
    "E32": "Ambulatory & Primary Health Care Services",
    "E40": "Reproductive Health Care Facilities & Allied Services",
    "E42": "Family Planning Centers",
    "E50": "Rehabilitative Medical Services",
    "E60": "Health Support Services",
    "E61": "Blood Banks",
    "E62": "Kidney Organ & Tissue Donation",
    "E65": "Health Screening",
    "E70": "Public Health",
    "E80": "Health & Well-being",
    "E86": "Patient Services & Advocacy",
    "E90": "Nursing",
    "E91": "Nursing Facilities",
    "E92": "Home Health Care",
    "E99": "Health - General & Rehabilitative N.E.C.",
    "F01": "Alliance/Advocacy Organizations",
    "F02": "Management & Technical Assistance",
    "F03": "Professional Societies & Associations",
    "F05": "Research Institutes & Public Policy Analysis",
    "F11": "Single Organization Support",
    "F12": "Fund Raising & Fund Distribution",
    "F19": "Nonmonetary Support N.E.C.",
    "F20": "Substance Abuse Dependency, Prevention & Treatment",
    "F21": "Alcoholism Dependency, Prevention & Treatment",
    "F22": "Drug & Substance Abuse Dependency, Prevention & Treatment",
    "F30": "Mental Health Treatment",
    "F31": "Psychiatric Hospitals",
    "F32": "Community Mental Health Centers",
    "F33": "Residential Mental Health Treatment",
    "F40": "Mental Health Disorders",
    "F42": "Community Mental Health Services",
    "F50": "Addictive Disorders",
    "F52": "Gambling Addiction",
    "F53": "Sex Addiction",
    "F54": "Technology Addiction",
    "F60": "Counseling & Support Groups",
    "F70": "Mental Health Associations & Crisis Intervention",
    "F80": "Health Support Services",
    "F99": "Mental Health, Crisis Intervention N.E.C.",
    "G01": "Alliance/Advocacy Organizations",
    "G02": "Management & Technical Assistance",
    "G03": "Professional Societies & Associations",
    "G05": "Research Institutes & Public Policy Analysis",
    "G11": "Single Organization Support",
    "G12": "Fund Raising & Fund Distribution",
    "G19": "Nonmonetary Support N.E.C.",
    "G20": "Birth Defects & Genetic Diseases",
    "G25": "Neuroscience Disorders",
    "G30": "Cancer",
    "G32": "Cancer Research",
    "G33": "Cancer Treatment",
    "G40": "Kidney Disease",
    "G41": "Kidney Disease Research",
    "G42": "Kidney Disease Treatment",
    "G43": "Kidney Disease Support",
    "G50": "Lung Disease",
    "G60": "Mental Health Disorders",
    "G70": "Genetic Diseases",
    "G80": "Heart & Circulatory System Diseases & Disorders",
    "G81": "Heart Disease Research",
    "G82": "Heart Disease Treatment",
    "G83": "Heart Disease Support",
    "G84": "Stroke",
    "G99": "Diseases, Disorders & Medical Disciplines N.E.C.",
    "H01": "Alliance/Advocacy Organizations",
    "H02": "Management & Technical Assistance",
    "H03": "Professional Societies & Associations",
    "H05": "Research Institutes & Public Policy Analysis",
    "H11": "Single Organization Support",
    "H12": "Fund Raising & Fund Distribution",
    "H19": "Nonmonetary Support N.E.C.",
    "H20": "Reproductive Health Care Facilities & Allied Services",
    "H30": "Family Planning Centers",
    "H40": "Birth Defects & Genetic Diseases",
    "H41": "Genetic Disease Research",
    "H42": "Genetic Disease Treatment",
    "H43": "Genetic Disease Support",
    "H44": "Infertility",
    "H50": "Sexually Transmitted Diseases",
    "H51": "HIV/AIDS",
    "H52": "Sexually Transmitted Disease Research",
    "H53": "Sexually Transmitted Disease Treatment",
    "H54": "Sexually Transmitted Disease Support",
    "H60": "Health Support Services",
    "H61": "Blood Banks",
    "H62": "Organ & Tissue Donation",
    "H80": "Health Screening",
    "H81": "Nursing",
    "H82": "Nursing Facilities",
    "H90": "Home Health Care",
    "H92": "Public Health",
    "H99": "Reproductive Health Care N.E.C.",
    "I01": "Alliance/Advocacy Organizations",
    "I02": "Management & Technical Assistance",
    "I03": "Professional Societies & Associations",
    "I05": "Research Institutes & Public Policy Analysis",
    "I11": "Single Organization Support",
    "I12": "Fund Raising & Fund Distribution",
    "I19": "Nonmonetary Support N.E.C.",
    "I20": "Crime & Legal Related",
    "I21": "Crime Prevention",
    "I23": "Criminal Justice System",
    "I30": "Law Enforcement Agencies & Police Departments",
    "I31": "Police Athletic Leagues",
    "I32": "Police Benevolent Associations",
    "I40": "Protection Against Abuse",
    "I43": "Sexual Abuse",
    "I44": "Spousal Abuse",
    "I50": "Victims' Services",
    "I51": "Victim & Witness Services",
    "I70": "Correctional Facilities",
    "I71": "Correctional Facilities",
    "I72": "Half-Way Houses",
    "I73": "Transitional Housing",
    "I80": "Prison Alternatives",
    "I83": "Bail & Legal Assistance",
    "I99": "Crime, Legal Related N.E.C.",
    "J01": "Alliance/Advocacy Organizations",
    "J02": "Management & Technical Assistance",
    "J03": "Professional Societies & Associations",
    "J05": "Research Institutes & Public Policy Analysis",
    "J11": "Single Organization Support",
    "J12": "Fund Raising & Fund Distribution",
    "J19": "Nonmonetary Support N.E.C.",
    "J20": "Employment Preparation & Procurement",
    "J21": "Vocational Guidance",
    "J22": "Job Training",
    "J30": "Employment",
    "J32": "Employment Training",
    "J33": "Vocational Rehabilitation",
    "J40": "Labor Unions",
    "J99": "Employment, Job Related N.E.C.",
    "K01": "Alliance/Advocacy Organizations",
    "K02": "Management & Technical Assistance",
    "K03": "Professional Societies & Associations",
    "K05": "Research Institutes & Public Policy Analysis",
    "K11": "Single Organization Support",
    "K12": "Fund Raising & Fund Distribution",
    "K19": "Nonmonetary Support N.E.C.",
    "K20": "Food & Nutrition",
    "K26": "Food Programs",
    "K28": "Food Banks & Pantries",
    "K30": "Public Health",
    "K31": "Health Support Services",
    "K34": "Blood Banks",
    "K35": "Organ & Tissue Donation",
    "K36": "Health Screening",
    "K40": "Nutrition",
    "K50": "Public Health",
    "K60": "Health Support Services",
    "K61": "Blood Banks",
    "K99": "Public Health N.E.C.",
    "L01": "Alliance/Advocacy Organizations",
    "L02": "Management & Technical Assistance",
    "L03": "Professional Societies & Associations",
    "L05": "Research Institutes & Public Policy Analysis",
    "L11": "Single Organization Support",
    "L12": "Fund Raising & Fund Distribution",
    "L19": "Nonmonetary Support N.E.C.",
    "L20": "Housing",
    "L21": "Housing Development, Construction & Management",
    "L22": "Low-Income & Subsidized Rental Housing",
    "L25": "Senior Citizens' Housing & Retirement Communities",
    "L30": "Housing Support Services",
    "L40": "Temporary Housing",
    "L41": "Homeless Shelters",
    "L50": "Emergency Shelter",
    "L80": "Home Improvement & Repairs",
    "L81": "Home Improvement",
    "L82": "Home Repairs",
    "L99": "Housing, Shelter N.E.C.",
    "M01": "Alliance/Advocacy Organizations",
    "M02": "Management & Technical Assistance",
    "M03": "Professional Societies & Associations",
    "M05": "Research Institutes & Public Policy Analysis",
    "M11": "Single Organization Support",
    "M12": "Fund Raising & Fund Distribution",
    "M19": "Nonmonetary Support N.E.C.",
    "M20": "Disaster Preparedness & Relief Services",
    "M23": "Public Safety, Disaster Preparedness & Relief",
    "M24": "Search & Rescue Squads",
    "M25": "Emergency Medical Services",
    "M30": "Community Disaster Preparedness",
    "M40": "Disaster Aid",
    "M41": "First Aid & Emergency Relief",
    "M42": "Shelter & Food",
    "M99": "Public Safety, Disaster Preparedness & Relief N.E.C.",
    "N01": "Alliance/Advocacy Organizations",
    "N02": "Management & Technical Assistance",
    "N03": "Professional Societies & Associations",
    "N05": "Research Institutes & Public Policy Analysis",
    "N11": "Single Organization Support",
    "N12": "Fund Raising & Fund Distribution",
    "N19": "Nonmonetary Support N.E.C.",
    "N20": "Recreational & Sporting Camps",
    "N30": "Physical Fitness & Community Recreational Facilities",
    "N31": "Parks & Playgrounds",
    "N32": "Parks",
    "N40": "Recreational Facilities",
    "N50": "Sports & Recreational Clubs",
    "N52": "Baseball & Softball",
    "N60": "Physical Fitness & Community Recreation",
    "N61": "Physical Fitness",
    "N62": "Community Recreation",
    "N65": "Community Centers",
    "N70": "Recreational & Sporting Camps",
    "N71": "Scouting Organizations",
    "N72": "Youth Community Service Clubs",
    "N80": "Recreational Facilities",
    "N99": "Recreation, Sports, Leisure, Athletics N.E.C.",
    "O01": "Alliance/Advocacy Organizations",
    "O02": "Management & Technical Assistance",
    "O03": "Professional Societies & Associations",
    "O05": "Research Institutes & Public Policy Analysis",
    "O11": "Single Organization Support",
    "O12": "Fund Raising & Fund Distribution",
    "O19": "Nonmonetary Support N.E.C.",
    "O20": "Youth Centers, Clubs, & Multipurpose Facilities",
    "O21": "Boys Clubs",
    "O30": "Recreational & Sporting Camps",
    "O31": "Scouting Organizations",
    "O40": "Youth Development Programs",
    "O50": "Recreational & Sporting Camps",
    "O99": "Youth Development N.E.C.",
    "P01": "Alliance/Advocacy Organizations",
    "P02": "Management & Technical Assistance",
    "P03": "Professional Societies & Associations",
    "P05": "Research Institutes & Public Policy Analysis",
    "P11": "Single Organization Support",
    "P12": "Fund Raising & Fund Distribution",
    "P19": "Nonmonetary Support N.E.C.",
    "P20": "Human Services",
    "P21": "American Red Cross",
    "P22": "Salvation Army",
    "P24": "Catholic Charities",
    "P26": "Lutheran Social Services",
    "P27": "Jewish Family Services",
    "P28": "United Way",
    "P29": "Family Services",
    "P30": "Children & Youth Services",
    "P31": "Adoption",
    "P32": "Foster Care",
    "P33": "Residential Care",
    "P40": "Temporary Shelter",
    "P42": "Homeless Shelters",
    "P43": "Family Violence Shelters",
    "P44": "Emergency Assistance",
    "P45": "Volunteers of America",
    "P46": "Domestic Violence Services",
    "P47": "Self-Help & Mutual Aid",
    "P50": "Personal Social Services",
    "P51": "Rehabilitation Services",
    "P52": "Services to Promote the Independence of Specific Populations",
    "P60": "Emergency Assistance",
    "P61": "Temporary Shelter",
    "P62": "Rescue",
    "P70": "Residential Care & Adult Day Programs",
    "P71": "Adult Day Care",
    "P72": "Residential Care",
    "P73": "Nursing Facilities",
    "P74": "Adult Day Programs",
    "P75": "Respite Care",
    "P80": "Family Services",
    "P81": "Child Day Care",
    "P82": "Early Childhood Programs & Services",
    "P84": "Parent & Teacher Groups",
    "P85": "Family Counseling",
    "P86": "Family Violence Shelters",
    "P87": "Family Services",
    "P99": "Human Services N.E.C.",
    "Q01": "Alliance/Advocacy Organizations",
    "Q02": "Management & Technical Assistance",
    "Q03": "Professional Societies & Associations",
    "Q05": "Research Institutes & Public Policy Analysis",
    "Q11": "Single Organization Support",
    "Q12": "Fund Raising & Fund Distribution",
    "Q19": "Nonmonetary Support N.E.C.",
    "Q20": "Religion Related, Spiritual Development",
    "Q21": "Protestant",
    "Q30": "Roman Catholic",
    "Q31": "Jewish",
    "Q32": "Islamic",
    "Q33": "Buddhist",
    "Q35": "Hindu",
    "Q40": "Religious Media & Communications",
    "Q42": "Interfaith Coalitions",
    "Q70": "Missionary Activities",
    "Q99": "Religion Related N.E.C.",
    "R01": "Alliance/Advocacy Organizations",
    "R02": "Management & Technical Assistance",
    "R03": "Professional Societies & Associations",
    "R05": "Research Institutes & Public Policy Analysis",
    "R11": "Single Organization Support",
    "R12": "Fund Raising & Fund Distribution",
    "R19": "Nonmonetary Support N.E.C.",
    "R20": "Civil Rights, Social Action & Advocacy",
    "R21": "Civil Rights",
    "R22": "Civil Liberties",
    "R23": "Women's Rights",
    "R24": "Minority Rights",
    "R25": "Seniors' Rights",
    "R26": "Lesbian & Gay Rights",
    "R28": "Children's Rights",
    "R30": "Military & Veterans Organizations",
    "R31": "Veterans' Organizations",
    "R32": "Military & Veterans' Rights",
    "R33": "Military & Veterans' Services",
    "R34": "Veterans' & Military Health Care",
    "R40": "Public Safety, Disaster Preparedness & Relief",
    "R50": "Voluntarism Promotion",
    "R60": "Community Improvement & Capacity Building",
    "R61": "Community Service Clubs",
    "R62": "Neighborhood Programs",
    "R63": "Economic Development",
    "R64": "Community Coalitions",
    "R65": "Urban & Community Economic Development",
    "R67": "Rural Development",
    "R99": "Civil Rights, Social Action & Advocacy N.E.C.",
    "S01": "Alliance/Advocacy Organizations",
    "S02": "Management & Technical Assistance",
    "S03": "Professional Societies & Associations",
    "S05": "Research Institutes & Public Policy Analysis",
    "S11": "Single Organization Support",
    "S12": "Fund Raising & Fund Distribution",
    "S19": "Nonmonetary Support N.E.C.",
    "S20": "Science & Technology",
    "S21": "Astronomy",
    "S22": "Astrobiology",
    "S30": "Earth Sciences",
    "S31": "Meteorology & Atmospheric Science",
    "S32": "Geology",
    "S40": "Biological & Life Sciences",
    "S41": "Ecology",
    "S50": "Chemical Sciences",
    "S80": "Physical & Mathematical Sciences",
    "S81": "Physics",
    "S82": "Mathematics",
    "S99": "Science & Technology N.E.C.",
    "T01": "Alliance/Advocacy Organizations",
    "T02": "Management & Technical Assistance",
    "T03": "Professional Societies & Associations",
    "T05": "Research Institutes & Public Policy Analysis",
    "T11": "Single Organization Support",
    "T12": "Fund Raising & Fund Distribution",
    "T19": "Nonmonetary Support N.E.C.",
    "T20": "Philanthropy, Charity & Voluntarism Promotion",
    "T21": "Philanthropy, Charity",
    "T22": "Fund Raising & Fund Distribution",
    "T23": "Voluntarism Promotion",
    "T30": "Public Foundations",
    "T31": "Community Foundations",
    "T40": "Corporate Foundations",
    "T50": "Private Grantmaking Foundations",
    "T70": "Federated Giving Programs",
    "T90": "Nonmonetary Support",
    "T99": "Philanthropy, Charity & Voluntarism Promotion N.E.C.",
    "U01": "Alliance/Advocacy Organizations",
    "U02": "Management & Technical Assistance",
    "U03": "Professional Societies & Associations",
    "U05": "Research Institutes & Public Policy Analysis",
    "U11": "Single Organization Support",
    "U12": "Fund Raising & Fund Distribution",
    "U19": "Nonmonetary Support N.E.C.",
    "U20": "Science & Technology Research Institutes",
    "U21": "Earth Sciences Research Institutes",
    "U22": "Environmental Research Institutes",
    "U30": "Biological & Life Sciences Research Institutes",
    "U31": "Genetics Research Institutes",
    "U32": "Marine & Aquatic Biology Research Institutes",
    "U33": "Medical & Health Sciences Research Institutes",
    "U34": "Neurology Research Institutes",
    "U36": "Physical & Mathematical Sciences Research Institutes",
    "U40": "Physical Sciences Research Institutes",
    "U41": "Astronomy Research Institutes",
    "U42": "Chemical Research Institutes",
    "U50": "Mathematical Research Institutes",
    "U99": "Science & Technology Research Institutes N.E.C.",
    "V01": "Alliance/Advocacy Organizations",
    "V02": "Management & Technical Assistance",
    "V03": "Professional Societies & Associations",
    "V05": "Research Institutes & Public Policy Analysis",
    "V11": "Single Organization Support",
    "V12": "Fund Raising & Fund Distribution",
    "V19": "Nonmonetary Support N.E.C.",
    "V20": "Social Science Research Institutes",
    "V21": "Anthropology Research Institutes",
    "V22": "Behavioral Research Institutes",
    "V24": "Demographic Research Institutes",
    "V25": "Economics Research Institutes",
    "V30": "Political Science Research Institutes",
    "V31": "Government & Public Administration Research Institutes",
    "V32": "Political Research Institutes",
    "V33": "Social Sciences Research Institutes",
    "V34": "Sociological Research Institutes",
    "V35": "Urban & Regional Planning Research Institutes",
    "V36": "Law & Legal Research Institutes",
    "V37": "Interdisciplinary Research Institutes",
    "V40": "Statistics & Non-Scientific Research Institutes",
    "V50": "Labor Studies & Industrial Relations Research Institutes",
    "V51": "Labor & Employment Research Institutes",
    "V52": "Labor Relations Research Institutes",
    "V53": "Industrial Relations Research Institutes",
    "V54": "Labor Economics Research Institutes",
    "V60": "Economics Research Institutes",
    "V61": "Business & Finance Research Institutes",
    "V62": "Consumer Research Institutes",
    "V63": "Management Research Institutes",
    "V65": "Marketing Research Institutes",
    "V70": "Regional Studies Research Institutes",
    "V80": "Area, Ethnic & Cultural Research Institutes",
    "V81": "African Studies Research Institutes",
    "V82": "Asian Studies Research Institutes",
    "V83": "Latin American Studies Research Institutes",
    "V84": "Middle Eastern Studies Research Institutes",
    "V85": "Native American Studies Research Institutes",
    "V86": "Caribbean Studies Research Institutes",
    "V99": "Social Science Research Institutes N.E.C.",
    "W01": "Alliance/Advocacy Organizations",
    "W02": "Management & Technical Assistance",
    "W03": "Professional Societies & Associations",
    "W05": "Research Institutes & Public Policy Analysis",
    "W11": "Single Organization Support",
    "W12": "Fund Raising & Fund Distribution",
    "W19": "Nonmonetary Support N.E.C.",
    "W20": "Public & Societal Benefit",
    "W22": "Military & Veterans' Organizations",
    "W24": "Military & Veterans' Services",
    "W30": "Military & Veterans' Health Care",
    "W40": "Public Safety, Disaster Preparedness & Relief",
    "W50": "Public Transportation Systems",
    "W60": "Military & Veterans' Services",
    "W61": "Veterans' Services",
    "W70": "Nonmonetary Support",
    "W80": "Public Safety, Disaster Preparedness & Relief N.E.C.",
    "W90": "Public & Societal Benefit N.E.C.",
    "W99": "Public & Societal Benefit N.E.C.",
    "X01": "Alliance/Advocacy Organizations",
    "X02": "Management & Technical Assistance",
    "X03": "Professional Societies & Associations",
    "X05": "Research Institutes & Public Policy Analysis",
    "X11": "Single Organization Support",
    "X12": "Fund Raising & Fund Distribution",
    "X19": "Nonmonetary Support N.E.C.",
    "X20": "Religion Related, Spiritual Development",
    "X21": "Protestant",
    "X30": "Roman Catholic",
    "X40": "Jewish",
    "X50": "Islamic",
    "X70": "Buddhist",
    "X80": "Hindu",
    "X81": "Religious Media & Communications",
    "X82": "Religious Media & Communications N.E.C.",
    "X99": "Religion Related N.E.C.",
    "Y01": "Alliance/Advocacy Organizations",
    "Y02": "Management & Technical Assistance",
    "Y03": "Professional Societies & Associations",
    "Y05": "Research Institutes & Public Policy Analysis",
    "Y11": "Single Organization Support",
    "Y12": "Fund Raising & Fund Distribution",
    "Y19": "Nonmonetary Support N.E.C.",
    "Y20": "Voluntarism Promotion",
    "Y22": "Public Foundations",
    "Y23": "Community Foundations",
    "Y24": "Corporate Foundations",
    "Y25": "Private Grantmaking Foundations",
    "Y30": "Public & Societal Benefit",
    "Y33": "Federated Giving Programs",
    "Y34": "Philanthropy, Charity & Voluntarism Promotion",
    "Y35": "Nonmonetary Support",
    "Y40": "Voluntarism Promotion",
    "Y42": "Philanthropy, Charity & Voluntarism Promotion",
    "Y43": "Public & Societal Benefit N.E.C.",
    "Y50": "Public & Societal Benefit N.E.C.",
    "Y99": "Public & Societal Benefit N.E.C.",
    "Z99": "Unknown"
};

export default ntee_codes;
