name: Update Database

on:
  schedule:
    # Run on the 1st of every month at midnight
    - cron: "0 0 1 * *"
  workflow_dispatch: # Manual trigger

permissions:
  contents: write  # Allows the workflow to commit and push changes to the repository

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo requests bs4 python-dotenv lxml

    # Step 4: Run the Python script located in the Data-management directory
    - name: Run db_update_runner.py
      run: |
        python Data-management/db_update_runner.py | tee output.log
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}

    # Step 5: Commit and push changes to zip_files_processed.txt
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Data-management/zip_files_processed.txt
        git commit -m "Update zip_files_processed.txt after running db_update_runner.py"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 6: Upload log artifact
    - name: Upload log artifact
      uses: actions/upload-artifact@v3
      with:
        name: output-log
        path: output.log
