name: Update Database

on:
  schedule:
    # Run on the 1st of every month at midnight
    - cron: "0 0 1 * *"
  workflow_dispatch: # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo requests bs4 python-dotenv lxml

    # Step 4: Run the Python script located in the Data-management directory
    - name: Run db_update_runner.py
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        python Data-management/db_update_runner.py
